/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phase3;

import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Yang-mac
 */
public class New_User extends javax.swing.JFrame {

    /**
     * Creates new form New_User
     */
	private String username = "";
	private String email = "";
	private String password = "";
	private String passConfirm = "";
	private String usrType = "";
	private String city = "";
	private String state = "";
	private String title = "";
	private ArrayList<String> cityNames = new ArrayList<String>();
	private ArrayList<String> stateNames = new ArrayList<String>();
	private ArrayList<String> userTypes = new ArrayList<String>();
	
    public New_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usrInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passInput = new javax.swing.JPasswordField();
        passConInput = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        titleInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        
        try {
            Connection conn = null;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabase",  "root", "123");
            System.out.println(conn.toString());
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM CITYSTATE;"; // populates the city and state dropdowns
            System.out.println("query: " + sql );
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
            	String city = rs.getString("City");
            	String state = rs.getString("State");
            	cityNames.add(city);
            	stateNames.add(state);
            }
            sql = "SELECT * FROM USERTYPE;";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
            	String temp = rs.getString(1);
            	userTypes.add(temp);
            }
            conn.close();
            } catch (Exception ex) {
            	JOptionPane.showMessageDialog(this,"Error in connectivity" );
        }

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("New User Registration");

        jLabel2.setText("Username");

        jLabel3.setText("Email Address");

        jLabel4.setText("Password");

        jLabel5.setText("Confirm Password");

        jLabel6.setText("User Type");
        
        String[] types = new String[userTypes.size()];
        for (int i = 0; i<userTypes.size(); i++) {
        	types[i] = userTypes.get(i);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(types));
        
        String[] cities = new String[cityNames.size()];
        for (int i = 0; i<cityNames.size(); i++) {
        	cities[i] = cityNames.get(i);
        }
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(cities));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("City:");

        jLabel8.setText("State:");

        jLabel9.setText("Title:");
        
        String[] states = new String[stateNames.size()];
        for (int i = 0; i<stateNames.size(); i++) {
        	states[i] = stateNames.get(i);
        }
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(states));
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(titleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel10.setText("Fill out this form if you choose city officials");

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(usrInput)
                                    .addComponent(passInput)
                                    .addComponent(passConInput, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usrInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passConInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // activate on click of "Create" button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	boolean success = true;
    	username = usrInput.getText();
    	email = emailInput.getText();
    	password = String.valueOf(passInput.getPassword());
    	passConfirm = String.valueOf(passConInput.getPassword());
    	usrType = (String) jComboBox1.getSelectedItem();
    	city = (String)jComboBox2.getSelectedItem();
    	state = (String)jComboBox3.getSelectedItem();
    	title =  titleInput.getText();
    	
    	try {
            Connection conn = null;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabase",  "root", "123");
            System.out.println(conn.toString());
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM USER WHERE Username='"+username+"';";
            System.out.println("query: " + sql );
            //stmt.executeQuery(sql);                       
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.next()) {
            	JOptionPane.showMessageDialog(new JFrame(), "Username already exists", "Registrition", JOptionPane.ERROR_MESSAGE);
            	success = false;
            	return;
            }
            conn.close();
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in connectivity" );
        }
    	
    	
    	if (!password.equals(passConfirm)) {
    		JOptionPane.showMessageDialog(new JFrame(), "Password mismatch", "Confirm Password", JOptionPane.ERROR_MESSAGE);
    		success = false;
    		return;
    	}
    	if (username.equals("")||email.equals("")||password.equals("")||passConfirm.equals("")||usrType.equals("")) {
    		JOptionPane.showMessageDialog(new JFrame(), "Please fill in all fields", "Missing Fields", JOptionPane.ERROR_MESSAGE);
    		success = false;
    		return;
    	}
    	if (usrType.equals("CityOfficial")) {
    		if (city.equals("") || state.equals("") || title.equals("")) {
    			JOptionPane.showMessageDialog(new JFrame(), "Please fill in all fields inside the box", "Error Message", JOptionPane.ERROR_MESSAGE);
    			success = false;
    			return;
    		}
    	}
    	
    	if (success==true) {
    		// write query into DB
    		try {
                Connection conn = null;
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabase",  "root", "123");
                System.out.println(conn.toString());
                Statement stmt = conn.createStatement();
                String sql = "INSERT INTO USER VALUES('"+username+"','"+email+"','"+password+"','"+usrType+"');";
                System.out.println("query: " + sql );
                stmt.executeUpdate(sql);                       
                if (usrType.equals("CityOfficial")) {
//                    String city = jComboBox2.getSelectedItem().toString();
//                    String state = jComboBox3.getSelectedItem().toString();
//                    String title = jTextField3.getText();
                    String sql2 = "INSERT INTO CITYOFFICIAL (Username,Title,City,State) VALUES('"+username+"','"+title+"','"+city+"','"+state+"');";
                    System.out.println("query: " + sql2);
                    stmt.executeUpdate(sql2);
                }
                if (usrType.equals("CityScientist")&&!title.equals("")) {
                	JOptionPane.showMessageDialog(this,"Please do not fille in the box area" );        			
                	return;
                }
                conn.close();
                } catch (Exception ex) {
                 JOptionPane.showMessageDialog(this,"Error in connectivity" );
                 return;
            }
    		
			JOptionPane.showMessageDialog(new JFrame(), "Your account has been created!");
			this.dispose(); // closes the registration form
			// opens the login form
			try {
		          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		              if ("Nimbus".equals(info.getName())) {
		                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
		                  break;
		              }
		          }
		      } catch (ClassNotFoundException ex) {
		          java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		      } catch (InstantiationException ex) {
		          java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		      } catch (IllegalAccessException ex) {
		          java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		          java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		      }
		      java.awt.EventQueue.invokeLater(new Runnable() {
		          public void run() {
		              new Login().setVisible(true);
		          }
		      });
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JPasswordField passConInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField usrInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField titleInput;
    // End of variables declaration//GEN-END:variables
}
